WIP Add support for hashtag suggestions
naumanni/naumanni pull request #109
Opened 2017-07-11 09:50 UTC by pe-ter-

## Pivotal Tracker
https://www.pivotaltracker.com/story/show/146845795

## TODO

- [ ] Fix test fail
- [ ] apply flowtype

2017-07-22 02:50 UTC, shnjp requested changes
パット見難しいところがあるのでコメントが欲しい。

2017-07-22 02:50 UTC, shnjp commented on src/js/api/MastodonAPISpec.es6
> +  hashtags: new schema.Entity('hashtags'),
`hashtags: [new schema.Entity('hashtag')],`のが良いんじゃないかなぁ

2017-07-22 02:50 UTC, shnjp commented on src/js/pages/components/AutoSuggestTextarea.es6
>    const staticHeightExceptTootTextArea = 400  // really rongh estimate...
rough?

2017-07-22 02:50 UTC, shnjp commented on src/js/pages/components/AutoSuggestTextarea.es6
> +  if(document.body != null) {
コメントがほしい

2017-07-22 02:50 UTC, shnjp commented on src/js/pages/components/AutoSuggestTextarea.es6
> +async function fetchAccountSuggestions(tokens: List<OAuthToken>, q: string, limit: number = MAX_SUGGESTIONS) {
ドキュメントを加えて下さい。
下のも。

2017-07-24 03:30 UTC, pe-ter- commented on src/js/pages/components/AutoSuggestTextarea.es6
>    const staticHeightExceptTootTextArea = 400  // really rongh estimate...
typoです...

2017-07-24 03:58 UTC, pe-ter- commented
@shnjp やりました

2017-07-24 09:36 UTC, shnjp approved these changes

2017-07-24 09:47 UTC, merged