WIP Add support for autosuggestion
naumanni/naumanni pull request #74
Opened 2017-05-30 08:49 UTC by pe-ter-

2017-05-30 09:07 UTC, shnjp requested changes
SuggestableTextareaみたいな感じで、Componentをわけられる？

fluxに載せなくて良いと思うけど、TootFormの肥大化はなるべく避けたい

2017-05-30 09:07 UTC, shnjp commented on src/js/pages/components/TootForm.es6
> +    const {requester} = this.props.tokens.get(0)
sendFromに設定している全TokenからsearchAccountするようにして欲しい。

2017-05-30 09:07 UTC, shnjp commented on src/js/utils/misc.es6
> +  if(!word || word.trim().length < 2 || word[0] !== '@') {
`startsWith('@')`のほうがシンプルじゃない？

2017-05-30 09:07 UTC, shnjp commented on src/js/utils/misc.es6
> +  word = word.trim().toLowerCase()
1行で良いのでは

2017-05-31 08:39 UTC, pe-ter- commented
いろいろなおしました

2017-06-01 08:14 UTC, shnjp requested changes
確定後に末尾に1スペース開けられますか？

つまり、確定後にそのまま文章を書けるようにしたい。

2017-06-01 08:15 UTC, shnjp commented
@Nnnnaho `postion:absolute`というかポップアップの形にできますか？
TootFormがガチャガチャサイズが変わるのはよろしくない

2017-06-01 08:24 UTC, pe-ter- commented
> 確定後に末尾に1スペース開けられますか？

やりました

2017-06-05 03:31 UTC, shnjp requested changes

2017-06-05 03:31 UTC, shnjp commented on src/js/pages/components/AutoSuggestTextarea.es6
> +    const tootFormContent = document.getElementsByClassName('tootForm-content')[0]
必ずrefを使うようにして欲しいんだけど、なんか理由がある？

2017-06-05 03:32 UTC, shnjp commented on src/js/pages/components/AutoSuggestTextarea.es6
> +    if(e.keyCode == KEY_ESC && !suggestionsHidden) {
ちょっと増えてきたので、とりあえず各操作がなんなのか、コメントを入れて欲しい

2017-06-05 03:33 UTC, shnjp commented on src/js/pages/components/AutoSuggestTextarea.es6
> +    }, 10)  // needs delay after update statusContent
10はどこから来た数字？
`requestAnimationFrame`ではダメですか？

2017-06-05 04:25 UTC, pe-ter- commented on src/js/pages/components/AutoSuggestTextarea.es6
> +    }, 10)  // needs delay after update statusContent
適当(目に見えてdelayしてる感がない程度にとかだったと思います)でした < 10
delaｙそもそも必要なかったっぽいので消します

2017-06-05 04:52 UTC, shnjp requested changes

2017-06-05 04:52 UTC, shnjp commented on src/js/pages/components/AutoSuggestTextarea.es6
> +    const node = document.getElementsByClassName('tootForm-status')[0]
`ReactDOM.findDOMNode(this.refs.statusContainer)`でDOMNodeが取れるとおもうんだけど、ダメだった？

2017-06-05 04:58 UTC, pe-ter- commented on src/js/pages/components/AutoSuggestTextarea.es6
> +    const node = document.getElementsByClassName('tootForm-status')[0]
いけました(setSelectionRangeがないよエラー出ましたが、そもそもこれ必要なかったので消します。)

2017-06-05 04:59 UTC, shnjp approved these changes

2017-06-05 05:03 UTC, merged