Add support for hashtag column
naumanni/naumanni pull request #78
Opened 2017-06-02 04:27 UTC by pe-ter-

## Pivotal Tracker
https://www.pivotaltracker.com/story/show/146427879

2017-06-02 05:12 UTC, shnjp requested changes

2017-06-02 05:12 UTC, shnjp commented on src/js/pages/columns/TalkColumn.es6
> +  onClickHashTag(tag, e) {
TimelineActionの同等メソッドを使うようにして欲しい

2017-06-02 06:00 UTC, pe-ter- commented
やりました

2017-06-05 05:05 UTC, shnjp approved these changes

2017-06-05 05:12 UTC, merged