WIP Add support for Mute,Block in UserDetail view
naumanni/naumanni pull request #83
Opened 2017-06-08 10:41 UTC by pe-ter-

## Pivotal Tracker
https://www.pivotaltracker.com/story/show/145743151

## TODO

- [ ] Mute/Unmute icon
- [ ] Block/UnBlock icon
- [ ] design(?)

2017-06-13 06:13 UTC, shnjp commented
@pe-ter- Icon追加したのでRebaseをお願いします。

2017-06-13 07:32 UTC, pe-ter- commented
@shnjp unmute, unblockはそれぞれどのアイコンつかいますか？
(みた感じ、mute -> 'volume-off', block -> 'block'という認識です)

<details>
<summary>volume 'off'感がない..?</summary>

![image](https://user-images.githubusercontent.com/4639852/27070843-9ce6e26a-5055-11e7-947d-759beb29d699.png)

</details>

2017-06-13 07:33 UTC, shnjp commented
その認識でよいです。
本家とあわせればよいかな、と。

2017-06-13 07:37 UTC, pe-ter- commented
un(mute|block)も同じアイコン使うという認識であってますか？

2017-06-13 07:38 UTC, shnjp commented
はい、un系のアイコンを思いつかないので、同じのを使ってください。

2017-06-13 07:38 UTC, pe-ter- commented
了解です

2017-06-13 08:01 UTC, pe-ter- commented
### Mute
![image](https://user-images.githubusercontent.com/4639852/27071910-ad646fe6-5059-11e7-9b8b-af197469e18b.png)

###  Block
![image](https://user-images.githubusercontent.com/4639852/27071937-c1a9e508-5059-11e7-9fcc-88ca091bb617.png)

2017-06-13 08:02 UTC, pe-ter- commented
@shnjp アイコン適用しました

2017-06-13 08:18 UTC, shnjp requested changes
すんません、いまさら指摘見つけました。

2017-06-13 08:18 UTC, shnjp commented on src/js/pages/components/UserDetail.es6
> +  getVisualForMuteRelationship(me) {
この2つの関数、メタ関数みたいなの作って共通部分まとめちゃって欲しい。

2017-06-13 08:18 UTC, shnjp commented on src/js/pages/components/UserDetail.es6
> +            <_FM id="user_detail.label.mute_all" />
全員、Mute済みだったら、「すべてからミュート解除」とする処理が抜けてます。
ブロックも同様

2017-06-13 08:18 UTC, shnjp commented on src/js/locales/ja.es6
> +  'user_detail.label.block': 'ブロック',
ボタン、メニュー項目などの動作を行うクリッカブルは
`XXXXする`
という表記に統一して欲しい

2017-06-14 03:23 UTC, pe-ter- commented
@shnjp やりました

2017-06-14 04:35 UTC, shnjp approved these changes

2017-06-14 04:36 UTC, merged