Show progress while sending media attached toot
naumanni/naumanni pull request #90
Opened 2017-06-13 04:56 UTC by pe-ter-

## Pivotal Tracker
https://www.pivotaltracker.com/story/show/145063923

2017-06-13 07:04 UTC, pe-ter- commented
@shnjp やりました

2017-06-13 08:42 UTC, shnjp requested changes
すんません、ちょっと要望が足りませんでした。

* プログレスバーは全体で100%にして欲しい。メディアが3枚あったら95%分を3枚が進めて、残り5%がpostStatus

* 文言は　「1つ目のメディアをアップロード中...」「2つ目の略」　のように、変えていって欲しい。

2017-06-14 11:07 UTC, pe-ter- commented
@shnjp やりました

2017-06-15 02:18 UTC, pe-ter- commented
複数垢でtootすると変になるのでまだでした

2017-06-15 03:18 UTC, pe-ter- commented
@shnjp やりました

2017-06-16 11:15 UTC, shnjp approved these changes

2017-06-21 09:37 UTC, shnjp commented
@pe-ter- スタイルが崩れてボタンの上に出てしまう。
まぁ僕が直すわ

2017-11-20 08:58 UTC, merged