Don't close drop down menu until mouse focused on menu
naumanni/naumanni pull request #94
Opened 2017-06-16 03:38 UTC by pe-ter-

## Pivotal Tracker
https://www.pivotaltracker.com/story/show/146604877

---

before | after
--- | ---
![before__fix dropdownmenu-mouseleave](https://user-images.githubusercontent.com/4639852/27210841-4a694108-5290-11e7-8fe1-61e03fc9db00.gif) | ![after__fix dropdownmenu-mouseleave](https://user-images.githubusercontent.com/4639852/27210842-50c7eab8-5290-11e7-951e-9fcff01db7b0.gif)

2017-06-21 10:19 UTC, pe-ter- commented
@shnjp rebaseしました

2017-06-23 02:43 UTC, pe-ter- commented
@shnjp tests fail直しました

2017-07-22 02:28 UTC, shnjp requested changes
名前関連がきになった。

2017-07-22 02:28 UTC, shnjp commented on src/js/pages/parts/DropdownMenuButton.es6
> +    this.setState({menuVisible: !this.state.menuVisible})
ここで、`enteredMenu`もfalseにしておくべきだと思う。

2017-07-22 02:28 UTC, shnjp commented on src/js/pages/parts/DropdownMenuButton.es6
> +      enteredMenu: false,
bool値なので、 is/has/hadとかを接頭辞にすべきだと思う。
`menuVisible`も同様に。

2017-07-22 02:28 UTC, shnjp commented on src/js/pages/parts/DropdownMenuButton.es6
> +  onEnteredMenu() {
onMouseLeaveと名前合わせて、`onMouseEntered`（だとonMouseLeavedだな...)みたいなのはどうでしょ

2017-07-24 06:46 UTC, pe-ter- commented
@shnjp やりました

2017-07-24 09:51 UTC, shnjp approved these changes

2017-07-24 10:54 UTC, merged